blank_issues_enabled: false
contact_links:
  - name: Blog
    url: https://blog.warp.dev/
    about: See our blog.
  - name: Changelog
    url: https://docs.warp.dev/help/changelog
    about: See our changelog.
  - name: Discord
    url: https://discord.gg/warpdotdev
    about: Discuss what you want to see in a modern terminal, report bugs, and brainstorm features for the Warp app.
  - name: Documentation
    url: https://docs.warp.dev/help/known-issues
    about: See our documentation, full Telemetry table, and known issues.
  - name: Licenses
    url: https://docs.warp.dev/help/licenses
    about: See the projects that we depend on and their open source licenses.
  - name: Warp website
    url: https://www.warp.dev/
    about: Our website.
